try and 1 / 0
except Exception, type(x) =<class 'ZeroDivisionError'>, x = division by zero, x.args = ('division by zero',)
raise TypeError('hello') from x
Traceback (most recent call last):
  File "ch33_raise_from.py", line 3, in <module>
    1 / 0
ZeroDivisionError: division by zero

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "ch33_raise_from.py", line 7, in <module>
    raise TypeError('hello') from x
TypeError: hello
